- hosts:
  - localhost
  - 127.0.0.1
  connection: local
  become: true
  tasks:
  - name: Install base items
    apt:
      name: ['vim', 'tmux', 'build-essential', 'ctags', 'imagemagick', 'libmysqlclient-dev', 'cmake', 'zsh']
  - name: change user shell to zsh
    become: true
    command: chsh -s /bin/zsh 'andy'
  - name: install rbenv
    repo: 'git@github.com:rbenv/rbenv.git'
    dest: '/home/andy/.rbenv'
