- hosts:
  - localhost
  - 127.0.0.1
  connection: local
  become: true
  tasks:
  - name: Install base items
    apt:
      name: ['vim', 'tmux', 'build-essential', 'ctags', 'imagemagick', 'libmysqlclient-dev', 'cmake', 'zsh']
